version: '3'

services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
    restart: always
    networks:
      - default
  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - default